version: 2

updates:
- package-ecosystem: npm
  directory: /
  target-branch: 2177_dependency_updates_bis
  schedule:
    interval: daily
- package-ecosystem: github-actions
  directory: /
  target-branch: 2177_dependency_updates_bis
  schedule:
    interval: daily
